
import "./globals.css";
import 'lenis/dist/lenis.css';
import { Inter } from 'next/font/google';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';
import LenisScroll from '@/components/LenisScroll';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter', 
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <div
          className="fixed top-0 left-0 w-full z-50 opacity-0 animate-fadeAfterIntro"
          style={{ animationDelay: '1.9s' }}
        >
          <NavBar />
        </div>
        <main>
          <LenisScroll>{children}</LenisScroll>
        </main>
        <Footer />
      </body>
    </html>
  );
}
