import "./globals.css";
import { Inter } from 'next/font/google';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter', 
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <div
          className="fixed top-0 left-0 w-full z-50 opacity-0 animate-fadeAfterIntro"
          style={{ animationDelay: '1.6s' }}
        >
          <NavBar />
        </div>
        <main>{children}</main>
      </body>
    </html>
  );
}
